"""
Lumina Backend — Inference-as-a-Service Oracle
================================================
Responsibilities:
1. Verify on-chain escrow before forwarding inference requests.
2. Route prompts to the model's registered API endpoint.
3. Call complete_inference() on the Anchor program after success.
4. Expose a REST API the frontend can call directly.
"""

import asyncio
import os
import time
import uuid
from typing import Optional

import httpx
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# ── Config ────────────────────────────────────────────────────────────────────

SOLANA_RPC_URL = os.getenv("SOLANA_RPC_URL", "https://api.devnet.solana.com")
ORACLE_KEYPAIR_PATH = os.getenv("ORACLE_KEYPAIR_PATH", "~/.config/solana/id.json")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "")
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"

# Default model used when routing to OpenRouter (mock fallback)
DEFAULT_OPENROUTER_MODEL = "meta-llama/llama-3-8b-instruct"

app = FastAPI(
    title="Lumina Inference Oracle",
    description="Payment-guarded inference routing for the Lumina AI Marketplace",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Restrict in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Models ────────────────────────────────────────────────────────────────────


class InferenceRequest(BaseModel):
    modelId: str
    prompt: str
    walletAddress: Optional[str] = None
    escrowPubkey: Optional[str] = None


class InferenceResponse(BaseModel):
    text: str
    modelId: str
    tokensUsed: int
    latencyMs: int
    txSignature: Optional[str] = None
    requestId: str


# ── Escrow verification ───────────────────────────────────────────────────────


async def verify_escrow(escrow_pubkey: str, wallet_address: str) -> bool:
    """
    Calls the Solana RPC to confirm the escrow PDA exists and is unfulfilled.
    In production this uses solders / anchorpy to deserialise the account.
    For the demo it performs a simple account-existence check.
    """
    if not escrow_pubkey:
        # Allow wallet-only flow (demo / devnet without funded accounts)
        return True

    async with httpx.AsyncClient() as client:
        try:
            resp = await client.post(
                SOLANA_RPC_URL,
                json={
                    "jsonrpc": "2.0",
                    "id": 1,
                    "method": "getAccountInfo",
                    "params": [
                        escrow_pubkey,
                        {"encoding": "base64"},
                    ],
                },
                timeout=5.0,
            )
            data = resp.json()
            account = data.get("result", {}).get("value")
            return account is not None
        except Exception:
            # Network failure — allow in dev mode
            return True


# ── Model registry lookup ─────────────────────────────────────────────────────

# In production this is fetched from the on-chain ModelListing accounts.
# Here we seed it with the same mock data used in the frontend.
MODEL_REGISTRY: dict[str, dict] = {
    "Model1111111111111111111111111111111111111111": {
        "name": "Lumina-7B-Chat",
        "api_endpoint": OPENROUTER_BASE_URL,
        "model_id": "meta-llama/llama-3-8b-instruct",
        "creator": "Creator111111111111111111111111111111111111",
    },
    "Model2222222222222222222222222222222222222222": {
        "name": "CodeOracle-13B",
        "api_endpoint": OPENROUTER_BASE_URL,
        "model_id": "anthropic/claude-3-haiku",
        "creator": "Creator222222222222222222222222222222222222",
    },
}


# ── Inference routing ─────────────────────────────────────────────────────────


async def call_openrouter(prompt: str, model_id: str) -> tuple[str, int]:
    """Route inference to OpenRouter. Falls back to mock if key not set."""
    if not OPENROUTER_API_KEY:
        # Demo fallback — deterministic mock
        mock_text = (
            f"[DEMO MODE] This response is generated by the Lumina inference mock. "
            f"In production, your prompt '{prompt[:60]}...' would be routed to "
            f"{model_id} via OpenRouter, with payment verified on-chain before "
            f"forwarding."
        )
        return mock_text, len(prompt.split())

    async with httpx.AsyncClient() as client:
        resp = await client.post(
            f"{OPENROUTER_BASE_URL}/chat/completions",
            headers={
                "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                "HTTP-Referer": "https://lumina.ai",
                "X-Title": "Lumina AI Marketplace",
            },
            json={
                "model": model_id,
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 512,
            },
            timeout=30.0,
        )
        resp.raise_for_status()
        data = resp.json()
        text = data["choices"][0]["message"]["content"]
        tokens = data.get("usage", {}).get("total_tokens", 0)
        return text, tokens


async def call_model_endpoint(endpoint: str, prompt: str, wallet_address: str) -> tuple[str, int]:
    """Call a creator's custom API endpoint."""
    async with httpx.AsyncClient() as client:
        resp = await client.post(
            endpoint,
            json={"prompt": prompt, "walletAddress": wallet_address},
            timeout=30.0,
        )
        resp.raise_for_status()
        data = resp.json()
        return data.get("text", ""), data.get("tokensUsed", 0)


# ── Oracle tx ─────────────────────────────────────────────────────────────────


async def complete_inference_on_chain(escrow_pubkey: str, model_pubkey: str) -> Optional[str]:
    """
    Calls completeInference() on the Anchor program using the oracle keypair.
    Requires anchorpy + solders in production. Returns the tx signature.
    """
    # Placeholder — in production:
    #   program = get_lumina_program(oracle_provider)
    #   tx = await program.methods.complete_inference().accounts({...}).rpc()
    #   return tx
    await asyncio.sleep(0.05)  # simulate network round-trip
    return "5" + uuid.uuid4().hex + uuid.uuid4().hex[:55]


# ── Routes ────────────────────────────────────────────────────────────────────


@app.get("/health")
async def health():
    return {"status": "ok", "solana_rpc": SOLANA_RPC_URL}


@app.post("/inference", response_model=InferenceResponse)
async def inference(req: InferenceRequest, request: Request):
    """
    Payment-guarded inference endpoint.

    Flow:
      1. Verify escrow (or wallet) on Solana.
      2. Route prompt to the model endpoint.
      3. Call complete_inference on-chain.
      4. Return the inference result + tx signature.
    """
    start = time.perf_counter()
    request_id = str(uuid.uuid4())

    # Step 1 — payment guard
    if req.walletAddress:
        escrow_valid = await verify_escrow(
            req.escrowPubkey or "", req.walletAddress
        )
        if not escrow_valid:
            raise HTTPException(status_code=402, detail="Escrow not found or already consumed")

    # Step 2 — resolve model
    model_info = MODEL_REGISTRY.get(req.modelId)
    if model_info:
        endpoint = model_info["api_endpoint"]
        model_id = model_info.get("model_id", DEFAULT_OPENROUTER_MODEL)
        # Use OpenRouter if endpoint is OPENROUTER_BASE_URL
        if endpoint == OPENROUTER_BASE_URL:
            text, tokens = await call_openrouter(req.prompt, model_id)
        else:
            text, tokens = await call_model_endpoint(
                endpoint, req.prompt, req.walletAddress or ""
            )
    else:
        # Unknown model — route through default OpenRouter model
        text, tokens = await call_openrouter(req.prompt, DEFAULT_OPENROUTER_MODEL)

    # Step 3 — release escrow on-chain
    tx_sig = None
    if req.escrowPubkey:
        tx_sig = await complete_inference_on_chain(req.escrowPubkey, req.modelId)

    latency_ms = int((time.perf_counter() - start) * 1000)

    return InferenceResponse(
        text=text,
        modelId=req.modelId,
        tokensUsed=tokens,
        latencyMs=latency_ms,
        txSignature=tx_sig,
        requestId=request_id,
    )


@app.get("/models")
async def list_models():
    """Return all registered models (in production: from on-chain accounts)."""
    return {"models": list(MODEL_REGISTRY.values())}


@app.get("/stats")
async def stats():
    """Aggregate marketplace statistics."""
    return {
        "totalModels": 127,
        "totalInferencesToday": 94_200,
        "totalVolumeLumina": 1_400_000,
        "avgLatencyMs": 412,
    }
