// Auto-generated IDL type for the Lumina Anchor program.
// Regenerate with `anchor build && anchor idl parse` after deploying.
export const IDL = {
  version: "0.1.0",
  name: "lumina",
  instructions: [
    {
      name: "initializeMarketplace",
      accounts: [
        { name: "marketplaceState", isMut: true, isSigner: false },
        { name: "luminaMint", isMut: false, isSigner: false },
        { name: "treasury", isMut: false, isSigner: false },
        { name: "admin", isMut: true, isSigner: true },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "feeBps", type: "u64" }],
    },
    {
      name: "registerModel",
      accounts: [
        { name: "modelListing", isMut: true, isSigner: false },
        { name: "stakeVault", isMut: true, isSigner: false },
        { name: "marketplaceState", isMut: true, isSigner: false },
        { name: "luminaMint", isMut: false, isSigner: false },
        { name: "creatorTokenAccount", isMut: true, isSigner: false },
        { name: "creator", isMut: true, isSigner: true },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "associatedTokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
        { name: "rent", isMut: false, isSigner: false },
      ],
      args: [
        { name: "name", type: "string" },
        { name: "description", type: "string" },
        { name: "apiEndpointUri", type: "string" },
        { name: "pricePerInference", type: "u64" },
        { name: "stakeAmount", type: "u64" },
      ],
    },
    {
      name: "requestInference",
      accounts: [
        { name: "inferenceEscrow", isMut: true, isSigner: false },
        { name: "escrowVault", isMut: true, isSigner: false },
        { name: "modelListing", isMut: true, isSigner: false },
        { name: "luminaMint", isMut: false, isSigner: false },
        { name: "userTokenAccount", isMut: true, isSigner: false },
        { name: "user", isMut: true, isSigner: true },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "associatedTokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
        { name: "rent", isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: "completeInference",
      accounts: [
        { name: "inferenceEscrow", isMut: true, isSigner: false },
        { name: "escrowVault", isMut: true, isSigner: false },
        { name: "modelListing", isMut: true, isSigner: false },
        { name: "model", isMut: false, isSigner: false },
        { name: "marketplaceState", isMut: true, isSigner: false },
        { name: "treasury", isMut: true, isSigner: false },
        { name: "creatorTokenAccount", isMut: true, isSigner: false },
        { name: "luminaMint", isMut: false, isSigner: false },
        { name: "oracle", isMut: false, isSigner: true },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: "refundInference",
      accounts: [
        { name: "inferenceEscrow", isMut: true, isSigner: false },
        { name: "escrowVault", isMut: true, isSigner: false },
        { name: "luminaMint", isMut: false, isSigner: false },
        { name: "userTokenAccount", isMut: true, isSigner: false },
        { name: "user", isMut: false, isSigner: true },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: "updateModelPrice",
      accounts: [
        { name: "modelListing", isMut: true, isSigner: false },
        { name: "creator", isMut: false, isSigner: true },
      ],
      args: [{ name: "newPrice", type: "u64" }],
    },
  ],
  accounts: [
    {
      name: "MarketplaceState",
      type: {
        kind: "struct",
        fields: [
          { name: "admin", type: "publicKey" },
          { name: "luminaMint", type: "publicKey" },
          { name: "treasury", type: "publicKey" },
          { name: "feeBps", type: "u64" },
          { name: "totalModels", type: "u64" },
          { name: "totalInferences", type: "u64" },
          { name: "totalVolume", type: "u64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "ModelListing",
      type: {
        kind: "struct",
        fields: [
          { name: "creator", type: "publicKey" },
          { name: "name", type: "string" },
          { name: "description", type: "string" },
          { name: "apiEndpointUri", type: "string" },
          { name: "pricePerInference", type: "u64" },
          { name: "stakedAmount", type: "u64" },
          { name: "totalInferences", type: "u64" },
          { name: "totalEarnings", type: "u64" },
          { name: "isActive", type: "bool" },
          { name: "createdAt", type: "i64" },
          { name: "bump", type: "u8" },
          { name: "stakeVaultBump", type: "u8" },
        ],
      },
    },
    {
      name: "InferenceEscrow",
      type: {
        kind: "struct",
        fields: [
          { name: "user", type: "publicKey" },
          { name: "model", type: "publicKey" },
          { name: "creator", type: "publicKey" },
          { name: "amount", type: "u64" },
          { name: "requestedAt", type: "i64" },
          { name: "isFulfilled", type: "bool" },
          { name: "bump", type: "u8" },
          { name: "vaultBump", type: "u8" },
        ],
      },
    },
  ],
  errors: [
    { code: 6000, name: "InvalidFeeBps", msg: "Fee basis points must be ≤ 10 000" },
    { code: 6001, name: "NameTooLong", msg: "Model name exceeds 64 characters" },
    { code: 6002, name: "DescriptionTooLong", msg: "Description exceeds 256 characters" },
    { code: 6003, name: "UriTooLong", msg: "API URI exceeds 128 characters" },
    { code: 6004, name: "ZeroPrice", msg: "Price must be greater than zero" },
    { code: 6005, name: "InsufficientStake", msg: "Stake amount below minimum (1 LUMINA)" },
    { code: 6006, name: "ModelNotActive", msg: "Model is not currently active" },
    { code: 6007, name: "AlreadyFulfilled", msg: "Inference already fulfilled or refunded" },
    { code: 6008, name: "RefundTooEarly", msg: "Refund window not yet elapsed (60 s)" },
    { code: 6009, name: "Unauthorized", msg: "Caller is not authorised to perform this action" },
  ],
} as const;
